app:
  PageSize: 10
  JwtSecret: 233
  PrefixUrl: http://127.0.0.1:8000

  RuntimeRootPath: cmd/runtime/

  ImageSavePath: upload/images/
  # MB
  ImageMaxSize: 5
  ImageAllowExts: .jpg,.jpeg,.png

  ExportSavePath: assets/export/
  QrCodeSavePath: assets/qrcode/
  FontSavePath: assets/fonts/
  #logs
  LogSavePath: logs/
  LogSaveName: logs
  LogFileExt: logs
  MaxAge: 7 * 24
  RotationTime: 24
  TimeFormat: 2006-01-02T15:04:05.000

server:
  #debug or release
  RunMode: debug
  Name: apiserver
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

database:
  Type: mongo
  DBHost: 127.0.0.1:27017
  AuthDb: mu_ti
  AuthUser: mu_ti
  AuthPass: mu_ti910217
  TimeOut: 60 * time.Second
  PoolLimit: 4096
  CollectionPrefix: muti_

redis:
  RedisHost: 127.0.0.1:6379
  RedisPass:
  MaxIdle: 30
  MaxActive: 30
  IdleTimeout: 200
